[images]
  remote_images = ["https://ext.same-assets.com/**", "https://ugc.same-assets.com/**", "https://source.unsplash.com/**", "https://images.unsplash.com/**"]

[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"
